### ISSUE TITLE
Enclosure ?

### ISSUE THREAD

**Issue by extremeshok** [maximilian-foerg/AM8-plus-Switchwire#1]
Since the guide rails are located on the outside, it would appear your design is not able to have a neat enclosure like a true switchwire.

**Comment by maximilian-foerg** [comment]
That is absolutely correct because that is not a true Switchwire. If you want a Switchwire, build a Switchwire. I would not recommend building an enclosure for this printer. The effort and cost of doing so is not worth it in the face of much more important upgrades. The printer much more urgently needs a better extruder, a better hotend, a lighter printhead, automatic bed leveling, and a better print bed. An enclosure is the last thing I would improve on this printer. With all these improvements, though, you're probably getting pretty close in price to a Voron Swicthwire, so you could have built a Swicthwire right away. I'm also not positioning this printer as an alternative to the Voron Switchwire.

**Comment by W141-ID** [comment]
While that is definitly true. I think it might be worth the effort to create a customized enclosure, since there are a lot of people out there already having upgraded much of the things you have mentioned. It is definitly not an alternative to the Switchwire but more a fun project for modders. There are already quite a few good ender 3 switchwire mods. I think this could also be a good one.

**Comment by maximilian-foerg** [comment]
Maybe there will be a V2 which brings the printer closer to a Switchwire. By arranging the aluminum extrusions in a different way, a Switchwire-like shape can be achieved, which makes a compact enclosure possible.

**Comment by W141-ID** [comment]
yeah definitly. If you need some help I am up for that. Coming also from germany should make the communication quite easy.
